name: All Tests

on:
  workflow_dispatch:
  pull_request:

jobs:
  unit_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - name: Add path
        run: echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x

      - name: Install latest shfmt
        run: GO111MODULE=on go get mvdan.cc/sh/v3/cmd/shfmt

      - name: Install latest shellspec
        run: wget -O- https://git.io/shellspec | sh -s -- --yes

      - name: Install shellcheck
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install shellcheck

      - name: Run all tests
        run: ./.github/run-tests.sh
